name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Simple test
        run: echo "GitHub Actions is working!" 